---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: update-opensuse-leap
    image: opensuse:leap
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x:
        - ANSIBLE0016
scenario:
  name: opensuse-leap
verifier:
  name: goss
  lint:
    name: yamllint
