---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: update-centos-6
    image: centos:6
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x:
        - ANSIBLE0016
scenario:
  name: centos-6
verifier:
  name: goss
  lint:
    name: yamllint
